# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='probability',
            field=models.IntegerField(default=0),
        ),
    ]
