# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 10:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adrs_clt',
            field=models.CharField(default=datetime.datetime(2016, 8, 9, 10, 53, 5, 178769, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
