# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 12:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_client_adrs_clt'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email_clt',
            field=models.CharField(default=datetime.datetime(2016, 8, 9, 12, 54, 43, 712598, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='login_clt',
            field=models.CharField(default=datetime.datetime(2016, 8, 9, 12, 54, 57, 674420, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='num_tel_clt',
            field=models.CharField(default=datetime.datetime(2016, 8, 9, 12, 55, 56, 784850, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
