# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20160809_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_vend', models.CharField(max_length=200)),
                ('prenom_vend', models.CharField(max_length=200)),
                ('adrs_vend', models.CharField(max_length=200)),
                ('num_tel_vend', models.CharField(max_length=200)),
                ('email_vend', models.CharField(max_length=200)),
                ('login_vend', models.CharField(max_length=200)),
            ],
        ),
    ]
