# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_vendeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_admin', models.CharField(max_length=200)),
                ('prenom_admin', models.CharField(max_length=200)),
                ('adrs_admin', models.CharField(max_length=200)),
                ('num_tel_admin', models.CharField(max_length=200)),
                ('email_admin', models.CharField(max_length=200)),
                ('login_admin', models.CharField(max_length=200)),
            ],
        ),
    ]
