# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_administrateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cat', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cmde', models.CharField(max_length=200)),
                ('id_clt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_fact', models.CharField(max_length=200)),
                ('id_clt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Client')),
                ('id_cmde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Commande')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet_msg', models.CharField(max_length=200)),
                ('contenu_msg', models.CharField(max_length=200)),
                ('date_msg', models.CharField(max_length=200)),
                ('login_clt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Client')),
            ],
        ),
        migrations.CreateModel(
            name='panier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_clt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_prod', models.CharField(max_length=200)),
                ('cat_prod', models.CharField(max_length=200)),
                ('desg_prod', models.CharField(max_length=200)),
                ('image_prod', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='panier',
            name='ref_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Produit'),
        ),
        migrations.AddField(
            model_name='commande',
            name='ref_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Produit'),
        ),
    ]
