# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20160809_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_cmde',
            field=models.DateTimeField(verbose_name='date commande'),
        ),
    ]
