# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20160809_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_clt', models.CharField(max_length=200)),
                ('prenom_clt', models.CharField(max_length=200)),
                ('adrs_clt', models.CharField(max_length=200)),
                ('num_tel_clt', models.CharField(max_length=200)),
                ('email_clt', models.CharField(max_length=200)),
                ('login_clt', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='tts',
        ),
    ]
