# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 15:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_categorie_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='cat_prod',
            field=models.ForeignKey(default=datetime.datetime(2016, 8, 9, 15, 32, 15, 128228, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='polls.Categorie'),
            preserve_default=False,
        ),
    ]
