# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_produit_cat_prod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='cat_prod',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
