# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20160809_1735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
